language: objective-c

osx_image: xcode9.1

env:
  matrix:
    - TEST_PLATFORM="platform=iOS Simulator,OS=9.3,name=iPhone 6s"
    - TEST_PLATFORM="platform=iOS Simulator,OS=10.3.1,name=iPhone 7"
    - TEST_PLATFORM="platform=iOS Simulator,OS=11.1,name=iPhone 8"

rvm:
    - 2.2.2

before_install:
    - gem install cocoapods -v '1.5.3'
    - gem install slather
    - gem install xcpretty -N --no-ri --no-rdoc
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
    - pod repo update
    - pod install
    - pod update

script:
    - set -o pipefail
    # next command is broken up multiline for ease of editing
    - >-
       xcodebuild -sdk iphonesimulator
       -destination "${TEST_PLATFORM}"
       -workspace Snowplow.xcworkspace
       -scheme Snowplow
       clean test
       | xcpretty

after_success: slather
